Fix linting issues
qbcore-framework/qb-recyclejob pull request #20
Opened 2022-05-13 07:29 UTC by TheiLLeniumStudios

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

2022-05-15 01:53 UTC, BerkieBb commented on client/main.lua
> +  local text = '[E] Clock In'
```suggestion
  local text = onDuty and '[E] Clock Out' or '[E] Clock In'
```

2022-05-15 01:53 UTC, BerkieBb commented on client/main.lua
> +  local text = '[E] Clock In'
This is a better way to handle it instead of having an if statement under it

2022-05-19 13:47 UTC, BerkieBb requested changes

2022-05-19 13:47 UTC, BerkieBb commented on client/main.lua
>      text = '[E] Clock Out'
Remove this if statement

2022-05-19 15:40 UTC, MatthewRorke commented on client/main.lua
>      text = '[E] Clock Out'
I went full REEEE

2022-05-19 15:44 UTC, BerkieBb approved these changes

2022-05-19 16:41 UTC, merged